### ISSUE TITLE
can I pass a parameters  ?

### ISSUE THREAD

**Issue by MichaelLiss** [dvpnt/cron-group#1]
I have your example code up and running... but the worker function I am using is noop

        noop = () => {

            console.log('called noop ');
        }

which is great... if you have a function that works with no data and is a global function that does nothing.
What would be better is if I could pass a parameter to the function, such as an _id. (or similar)

My code is your code:

        group.add({
            name: 'foo',
            schedule: '* * * * * *',
            worker: noop,
        });

        group.on('run', ({name, runnedBy}) => {
            console.log(`${name} is runned by ${runnedBy}`);
        });
        
        group.on('complete', ({name, runnedAt, completedAt}) => {
            const prettyTime = Math.floor((completedAt - runnedAt) / 1000);
            console.log(`${name} successfully completed in ${prettyTime}s`);
        });
        
        group.on('error', ({name, err}) => {
            console.error(`${name} is completed with error\n${err.stack || err}`);
        });
        
        group.start();

**Comment by qlba** [comment]
```js
    ...
        worker: () => noop(_id),
    ...
```
Is that what you mean?

**Comment by MichaelLiss** [comment]
perfect !  thanks !

**Comment by fleg** [comment]
Ok, I'm closing this
